config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  root to: 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search', defaults: { format: 'js' }
  get 'friends_list', to: 'users#my_friends_list'
  get 'search_friend', to: 'users#search', defaults: { format: 'js' }
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
require 'httparty'

class Stock < ApplicationRecord
    has_many :user_stocks
    has_many :users, through: :user_stocks

    validates :name, :ticker, presence: true

    def self.company_lookup(ticker_symbol)
        response = HTTParty.get("https://www.alphavantage.co/query?function=OVERVIEW&symbol=#{ticker_symbol}&apikey=#{Rails.application.credentials.alpha_client[:api_key]}")
        if response.code == 200
          response.parsed_response['Name']
        else
          nil
        end
    end

    def self.new_lookup(ticker_symbol)
        response = HTTParty.get("https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=#{ticker_symbol}&apikey=#{Rails.application.credentials.alpha_client[:api_key]}")
        if response.code == 200 && response.parsed_response['Global Quote']
          last_price = response.parsed_response['Global Quote']['05. price']
          name = company_lookup(ticker_symbol)
          new(ticker: ticker_symbol, name: name, last_price: last_price)
        else
          nil
        end
      end

    def self.check_db(ticker_symbol)
      where(ticker: ticker_symbol).first
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks 
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def  under_stock_limit?
    stocks.count < 10
  end
         
  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end
  
  def full_name
    if first_name || last_name
      "#{first_name} #{last_name}"
    else 
      "Anonymous"
    end
  end

  def self.search(param)
    param.strip! 
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back 
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end
  
  def self.email_matches(param)
    matches('email', param)
  end
  
  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end
  
  
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected 

    def configure_permitted_parameters 
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
    
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    #friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: params[:friend])
    if current_user.save
      flash[:notice] = "Following friend"
    else 
      flash[:alert] = "There was something wrong with the tracking request"
    end 
    redirect_to friends_list_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "Stopped following"
    redirect_to friends_list_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController 
    protect_from_forgery except: :search

    def search 
        if params[:stock].present? 
            if params[:stock].length <= 5 && params[:stock].length >= 2
                @stock = Stock.new_lookup(params[:stock]) 
                if @stock 
                    respond_to do |format|
                        format.js {render partial: 'users/result'}
                    end
                end
            else 
                respond_to do |format|
                flash.now[:alert] = "It seems that the symbol you have entered does not exist, check if you spelled it correctly"
                format.js {render partial: 'users/result'}
                end
            end
        else 
            respond_to do |format|
                flash.now[:alert] = "Please enter a symbol to search"
                format.js {render partial: 'users/result'}
                end
        end
    end
    
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
    def create
        stock = Stock.check_db(params[:ticker])
        if stock.blank? 
            stock = Stock.new_lookup(params[:ticker])
            stock.save 
        end 
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:notice] = "Stock #{stock.name} was successfully added to you portfolio"
        redirect_to my_portfolio_path
    end

    def destroy
        stock = Stock.find(params[:id])
        user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
        user_stock.destroy
        flash[:notice] = "#{stock.ticker} was successfully removed from portfolio"
        redirect_to my_portfolio_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery except: :search

  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends_list
    @friends = current_user.friends
  end

  def show 
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def search 
    if params[:friend].present? 
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends 
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else 
        respond_to do |format|
          flash.now[:alert] = "Couldn't find user"
          format.js { render partial: 'users/friend_result' }
        end
      end
    else 
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend name or email to search"
        format.js { render partial: 'users/friend_result' }
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 
    def index 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_list.html.erb
 <div class="row mt-3">
        <div class="col-9">
            <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th scope="col">Email</th>
                    <th scope="col">First name</th>
                    <th scope="col">Last name</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @friends.each do |friend| %>
                    <tr>
                        <td><%= friend.email %></td>
                        <td><%= friend.first_name %></td>
                        <td><%= friend.last_name %></td>
                        <td>
                            <%= link_to 'View profile', user_path(friend),class: "btn btn-sm btn-success" %>
                            <%= link_to 'Stop following', friendship_path(friend), method: :delete,data: {confirm: "Are you sure? "}, class: "btn btn-sm btn-warning" %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
            </table>
        </div>
    </div>

app/views/layouts/_messages.html.erb
<% if notice %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <p class="notice"><%= notice %></p>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

<% if alert %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <p class="alert"><%= alert %></p>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <%= link_to 'FinanceTracker', root_path, class: "navbar-brand" %>
    <% if current_user %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'My portfolio', my_portfolio_path, class: "nav-link #{'active' if request.path == my_portfolio_path}" %>
          </li>
          <li class="nav-item">
            <%= link_to 'My friends', friends_list_path, class: "nav-link #{'active' if request.path == friends_list_path}" %>
          </li>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <ul class="dropdown-menu">
              <li>
               <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                 <%= fa_icon 'edit' %> Edit profile
               <% end %>
               </li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item m-2">  
              <%= fa_icon 'user'%> <%= current_user.full_name %>
          </li>
          <li class="nav-item">
            <%= link_to("Logout", destroy_user_session_path, 
                        class: "btn btn-xs btn-danger logout-button ", method: :delete) %>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
 <div class="row mt-3">
        <div class="col-9">
            <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th scope="col">Ticker</th>
                    <th scope="col">Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @tracked_stocks.each do |stock| %>
                    <tr>
                        <th scope="row"> <%= stock.ticker %> </th>
                        <td><%= stock.name %></td>
                        <td><%= stock.last_price %></td>
                        <td>
                            <% if current_user.can_track_stock?(stock.ticker)%>
                                <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: stock.ticker), class: "btn btn-xs btn-success", method: :post %>
                            <% elsif current_user.id != @user.id%>
                                <span class="badge text-bg-secondary">
                                    You are already tracking 
                                    <% if !current_user.under_stock_limit? %>
                                        10 stocks 
                                    <% end %>
                                    <% if current_user.stock_already_tracked?(stock.ticker) %>
                                        this stock 
                                    <% end %>
                                </span>
                            <% end %>
                            <%if current_user.id == @user.id%>
                                <%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: "Are you sure? "}, class: "btn btn-sm btn-warning" %>
                            <%end%>    
                        </td>
                    </tr>
                <% end %>
            </tbody>
            </table>
        </div>
    </div>

app/views/users/_friend_result.html.erb
<div class="results-block">
    <%= render 'layouts/messages'%>
</div>


<%if @friends%>
    <div class="card card-header results-block">
        <table class="col-md-12">
            <tbody>
                <% @friends.each do |friend| %>
                    <tr>
                        <td><strong>Name: </strong><%=friend.full_name%></td>
                        <td><strong>Email: </strong><%=friend.email%></td>
                        <td><strong>Actions: </strong><%= link_to "View Profile", user_path(friend), class: "btn btn-sm btn-success" %>
                        <% if current_user.not_friends_with?(friend.id) %>
                            <%= link_to 'Follow friend?', friendships_path(friend: friend), class: "btn btn-sm btn-success", method: :post %>
                        <%else%>
                            <span class="badge text-bg-light">
                                You are friends already
                            </span>
                        <%end%>
                        </td>
                    </tr>    
                <%end%>
            </tbody>
        </table>
    </div>
<%end%>

app/views/users/_friend_result.js.erb
document.querySelector('#results').innerHTML = "<%= escape_javascript(render 'users/friend_result.html') %>"

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = "<%= escape_javascript(render 'users/results.html') %>"

app/views/users/_results.html.erb
<div class="results-block">
    <%= render 'layouts/messages'%>
</div>


<%if @stock%>
    <div class="card card-header results-block">
        <strong>Symbol: </strong><%=@stock.ticker%>
        <strong>Name: </strong><%=@stock.name%>
        <strong>Price: </strong><%=@stock.last_price%>
        <% if current_user.can_track_stock?(@stock.ticker)%>
            <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-xs btn-success", method: :post %>
        <% else %>
            <span class="badge text-bg-secondary">
                You are already tracking 
                <% if !current_user.under_stock_limit? %>
                    10 stocks 
                <% end %>
                <% if current_user.stock_already_tracked?(@stock.ticker) %>
                    this stock 
                <% end %>
            </span>
        <% end %>
    </div>
<%end%>

app/views/users/my_friends_list.html.erb
<h1>Friends</h1>
<div class="search-area">
    <h3>Search Friends</h3>
    <%= form_tag search_friend_path, remote: true, method: :get do %>
        <div class="form-group row">
            <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :friend, params[:friend], placeholder: "Name or email", autofocus: true, class: "form-control form-control-lg"%>
            </div>
            <div class="col-sm-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <%end%>
</div>
    <div id="results">
</div>
<% if !@friends.empty? %>
   <%= render 'friends/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>
<div class="search-area">
    <h3>Search Stocks</h3>
    <%= form_tag search_stock_path, remote: true, method: :get do %>
        <div class="form-group row">
            <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg", onkeyup: "this.value = this.value.replace(/[^a-zA-Z]/g, '').toUpperCase();" %>
            </div>
            <div class="col-sm-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <%end%>
</div>
    <div id="results">
</div>
<% if !@tracked_stocks.empty? %>
   <%= render 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>

<div class="results-block">
    <%= render 'layouts/messages'%>
</div>


<div class="card card-header results-block">
    <table class="col-md-12">
        <tbody>
            <tr>
                <td><strong>Name: </strong><%=@user.full_name%></td>
                <td><strong>Email: </strong><%=@user.email%></td>
                <td>
                <% if current_user.not_friends_with?(@user.id) %>
                    <%= link_to 'Follow friend?', friendships_path(friend: @user), class: "btn btn-sm btn-success", method: :post %>
                <%else%>
                    <span class="badge text-bg-light">
                        You are friends already
                    </span>
                <%end%>
                </td>
            </tr>    
        </tbody>
    </table>
</div>

<% if !@tracked_stocks.empty? %>
   <%= render 'stocks/list' %>
<% else %>
    <p class="lead">This user is not tracking any stocks</p>
<%end%>

app/views/welcome/index.html.erb
<h1>Welcome to the Finance Tracker app</h1>

<p>Create a welcome page</p>